name: CI

on:
  push:
    branches: [ '**', '!main' ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: .github/workflows/java-version
          cache: 'maven'
          server-id: ossrh

      - name: Verify
        run: ./mvnw -B -P ci clean verify
