name: Publish to Maven Central and GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK for Maven Central
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: .github/workflows/java-version
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.CONER_CI_CD_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Maven Central
        run: ./mvnw -B -P cd,deploy-sonatype deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.CONER_CI_CD_PASSPHRASE }}

      - name: Setup JDK for GitHub Packages
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: .github/workflows/java-version
          cache: 'maven'

      - name: Publish to GitHub Packages
        run: ./mvnw -B -P cd,deploy-github deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.CONER_CI_CD_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
